# Generated by Django 5.2.7 on 2025-12-02 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_teaminvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaminvitation',
            unique_together=set(),
        ),
    ]
