# Generated by Django 5.2.7 on 2026-03-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_screenshot'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='screenshot',
            new_name='management__user_id_b4054d_idx',
            old_name='management_s_user_id_e7e6c0_idx',
        ),
        migrations.RenameIndex(
            model_name='screenshot',
            new_name='management__time_en_6ddea8_idx',
            old_name='management_s_time_en_0219b6_idx',
        ),
        migrations.RenameIndex(
            model_name='screenshot',
            new_name='management__project_71edcb_idx',
            old_name='management_s_project_6ece43_idx',
        ),
    ]
