# Generated by Django 5.2.7 on 2026-03-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0002_useraccesslog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useraccesslog',
            new_name='admin_site__user_id_3fcb1d_idx',
            old_name='admin_site__user_cr_8d26cb_idx',
        ),
        migrations.RenameIndex(
            model_name='useraccesslog',
            new_name='admin_site__event_t_2a7a85_idx',
            old_name='admin_site__event_t_529c39_idx',
        ),
    ]
